version: "2.2"

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: gio_app
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx:1.25
    container_name: gio_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
